### Create region
POST localhost:8080/profile/create
Content-Type: application/json

{
  "name": "Di",
  "surname": "Zero",
  "email": "20041017i@gmail.com",
  "phone": "+998994123320",
  "password": "20020102tT",
  "role": "ROLE_ADMIN"
}

### Get all
GET localhost:8080/profile/all

### update profile
PUT localhost:8080/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTY5MTM1MzAsImlkIjoxNSwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNjk5OTkzMCwiaXNzIjoiS3VuVXpUZXN0In0.MGFeAnyB6m9ExSdDDjCPZkfilYhwSzU-_xUHLNv6BvR7krDzxkVEWj94rzwypfSxYunvDLnG67hkMIMoRdGfCQ

{
  "name": "Dizzy",
  "surname": "Say"
}

### delete profile by id
DELETE localhost:8080/profile/delete/153